
name: Test Code

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run:
          pip install -r Porjetcs/requirements.txt &&
          python main.py ${{ secrets.GITHUB_API_KEY }}
